# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml uv.lock ./

# Install Python dependencies
RUN pip install --no-cache-dir httpx mcp[cli]>=1.6.0 python-dotenv

# Copy remaining source
COPY . .

# Default entrypoint
CMD ["python", "dart.py"]
